### ISSUE TITLE
add support for backup of HA etcd cluster

### ISSUE THREAD

**Issue by dlbewley** [redhat-cip/rcip-openshift-scripts#1]
This looks super handy, backup/etcd/get_env.py doesn't work in the case where OSE cluster is HA with a dedicated etcd cluster and master nodes.
- `master:/etc/origin/master/master-config.yaml`

``` yaml
etcdClientInfo:
  ca: master.etcd-ca.crt
  certFile: master.etcd-client.crt
  keyFile: master.etcd-client.key
  urls:
    - https://ose-prod-etcd-01.example.com:2379
    - https://ose-prod-etcd-02.example.com:2379
    - https://ose-prod-etcd-03.example.com:2379
etcdStorageConfig:
  kubernetesStoragePrefix: kubernetes.io
  kubernetesStorageVersion: v1
  openShiftStoragePrefix: openshift.io
  openShiftStorageVersion: v1
```

I happened to have installed etcd on a master just to have `etcdctl` handy, but  `/etc/etcd/etcd.conf` gives misleading info about where to find `stor`.

```
# legit
[root@ose-prod-etcd-01 ~]# grep ETCD_DATA_DIR /etc/etcd/etcd.conf
ETCD_DATA_DIR=/var/lib/etcd/

# bogus
[root@ose-prod-master-01 ~]# grep ETCD_DATA_DIR /etc/etcd/etcd.conf
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
```
